### ISSUE TITLE
Duvidas

### ISSUE THREAD

**Issue by Ryannnkl** [Anthhon/seletos-sistema-de-ponto#13]
## Como que roda? 
 venho do mundo js, pra rodar um projeto na minha cabeça é npm run start, django eu tive que pesquisar e inclusive achei que estivesse quebrado ja que eu rodei assim que aprendi como que rodava pesquisando, e deu erro, só ai que descobri que precisava rodar migrations, acho interessante que tenha esse passo a passo no readme do projeto
 
Qual é o admin? 

user e senha até agora não achei o login referente

**Comment by Anthhon** [comment]
Para acessar a página de Admin é necessário que seja criado uma conta através do terminal, o comando é:

`python manage.py createsuperuser`

Em seguida você vai precisar digitar algumas informações como e-mail, nome e senha. _O e-mail normalmente só é usado para recuperação de contas, então em caso de teste pode deixar o campo vazio sem problemas._

Após isso só acessar o endereço local que você está rodando a aplicação e digitar as credenciais que você definiu.

Caso tenha alguma dificuldade com o processo esse link aqui pode ajudar:
[Como criar super usuário no Django](https://www.educative.io/answers/how-to-create-a-superuser-in-django)

**Comment by Anthhon** [comment]
Sobre a questão da documentação, achei uma ótima sugestão, apesar de que o projeto anda meio abandonado, vou considerar adicionar um passo a passo assim que possível, caso você se sinta confiante em fazê-lo eu seria grato em aceitar o pull request. O programa tem código-livre e qualquer melhoria é bem-vinda :)

**Comment by Ryannnkl** [comment]
Hoje no trabalho tava procurando um app assim e encontrei esse pra ajudar na empresa que trabalho, tem potencial para ser grande, tem vários softwares desse no mercado, muitos deles pagos e muitos são caros, um open-source faria muito sucesso eu tenho certeza, obrigado!
